# -*- coding: utf-8 -*-
"""BertTopic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiEOTgkeKOXU1wBKjUWBx6Xz7DODo8GM
"""

!pip install bertopic

!pip install gensim

from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import glob
import os
import gensim
from bertopic import BERTopic
import re
from nltk.tokenize import sent_tokenize
import requests

import nltk
nltk.download('punkt_tab')

#Mounting the drive
import os

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define the base directory for your meetings
base_dir = "/content/drive/MyDrive/Emergency_Meeting_Deepgram"

# Use glob to collect all file paths matching the pattern:
# This pattern assumes directories like meeting/episode_1, meeting/episode_2, etc.
file_paths = glob.glob(os.path.join(base_dir, "**", "*.txt"), recursive=True)

#Reading the files
def read_file(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
        return content

#Making the documents into a list
documents = [read_file(fp) for fp in file_paths]

#Creating the DF
df = pd.DataFrame({"file_path": file_paths, "text": documents})

file_names = []

for path in df['file_path']:
    match = re.search(r'[^\\/]+$', path)
    file_name = match.group() if match else None
    file_names.append(file_name)

# Add it back to the DataFrame
df['file_name'] = file_names

df.head()

#making snippet DF
import re
from nltk.tokenize import sent_tokenize

# Example structure
#df = pd.DataFrame({
   # 'doc_id': ['video_001', 'video_002'],
   # 'text': [transcript1, transcript2]})

def chunk_dataframe(df, max_chars=800):
    snippets = []

    for idx, row in df.iterrows():
        doc_id = row['file_name']
        text = re.sub(r'\s+', ' ', row['text']).strip()
        sentences = sent_tokenize(text)

        chunk, chunk_id = "", 0
        for sentence in sentences:
            if len(chunk) + len(sentence) <= max_chars:
                chunk += " " + sentence
            else:
                snippets.append({
                    'doc_id': doc_id,
                    'chunk_id': chunk_id,
                    'text': chunk.strip()
                })
                chunk_id += 1
                chunk = sentence
        if chunk:
            snippets.append({
                'doc_id': doc_id,
                'chunk_id': chunk_id,
                'text': chunk.strip()
            })

    return pd.DataFrame(snippets)

chunked_df = chunk_dataframe(df)

chunked_df.shape

chunked_df['lower_text'] = chunked_df['text'].str.lower()

df_clean.shape

#prepocessing
stopwords_list = requests.get("https://gist.githubusercontent.com/rg089/35e00abf8941d72d419224cfd5b5925d/raw/12d899b70156fd0041fa9778d657330b024b959c/stopwords.txt").content
stop_words = set(stopwords_list.decode().splitlines())

custom_stopwords = stop_words.union({"gon", "yeah", "fucking","bro", "shit","thing", "wan","ha",
                                     "andrew", "tate", "person","year", "day","lot","fuck",
                                     "doe", "time", "good", "talk", "gonna","people", "things",
                                     "wanna"})
custom_stopwords=list(custom_stopwords)

vectorizer = CountVectorizer(stop_words=custom_stopwords

                             )

#to reduce the impact of frequent words.
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

#lemma
import spacy
nlp = spacy.load("en_core_web_sm")

def lemmatize_text(text):
    doc = nlp(text)  # Process text with spaCy
    return " ".join([token.lemma_ for token in doc])  # Convert words to base form

chunked_df["lemma_text"] = chunked_df["text"].apply(lemmatize_text)

#making the documents to a list
documents = chunked_df["lower_text"].tolist()

chunked_df.head()

import gensim
from gensim.models.phrases import Phrases, Phraser
from nltk.tokenize import word_tokenize


# Tokenize each sentence
tokenized_texts = [word_tokenize(text.lower()) for text in documents]

# Train bigram model
bigram_model = Phrases(tokenized_texts, min_count=10, threshold=50)
bigram_phraser = Phraser(bigram_model)

# Apply bigram model
processed_token_lists = [bigram_phraser[doc] for doc in tokenized_texts]

# Convert processed tokens back into full sentences
processed_texts = [" ".join(tokens) for tokens in processed_token_lists]

chunked_df['bigram_nolemmatext'] = processed_texts
#print(processed_texts)

#saving for later
file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv"
chunked_df.to_csv(file_path, index=False)

documents = chunked_df["bigram_nolemmatext"].tolist()

chunked_df.head()

#BERT model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")  # Lightweight but effective
topic_model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       #nr_topics=15,
                       vectorizer_model=vectorizer, # use the updated vectorizer with adjusted max_df
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30, #15-30
                                       n_components=2, #2 or 5
                                       metric='cosine',
                                       min_dist=0.0), #can lower to 0.0–0.05 if you want tighter local clustering or increase for more spread-out clusters
                       hdbscan_model=HDBSCAN(min_cluster_size=45, #Try 15–50. A sweet spot is often around 25–40
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

#Increase min_cluster_size to prevent small, repetitive clusters.
#Switch metrics (cosine, euclidean) to see how different distance measures affect clustering.

topics, probs = topic_model.fit_transform(documents)

"""## Loading Saved Models"""

#topic_model.save("/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics", save_embedding_model=True)
topic_model = BERTopic.load("/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics") #Tate_model_nolemma"

topic_model.reduce_topics(documents, nr_topics=6)

tm_nolemma = topic_model.get_topic_info()

tm_nolemma

"""## Coherence Scores"""

cleaned_docs = topic_model._preprocess_text(documents)

analyzer = topic_model.vectorizer_model.build_analyzer()
tokens = [analyzer(doc) for doc in cleaned_docs]

from gensim import corpora
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]

#from bertopic import BERTopic
from gensim.models import CoherenceModel

coherence_scores = []

for n_topics in range(3, 30):
    # Fit and reduce topics
    model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       #nr_topics=15,
                       vectorizer_model=vectorizer, # use the updated vectorizer with adjusted max_df
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30, #15-30
                                       n_components=2, #2 or 5
                                       metric='cosine',
                                       min_dist=0.0), #can lower to 0.0–0.05 if you want tighter local clustering or increase for more spread-out clusters
                       hdbscan_model=HDBSCAN(min_cluster_size=45, #Try 15–50. A sweet spot is often around 25–40
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

    topics, _ = model.fit_transform(documents)
    model = model.reduce_topics(documents, nr_topics=n_topics)

    # Extract topic words
    topic_words = [
        [word for word, _ in model.get_topic(topic_id)]
        for topic_id in model.get_topics().keys()
        if topic_id != -1
    ]

    # Calculate coherence
    cm = CoherenceModel(
        topics=topic_words,
        texts=tokens,
        corpus=corpus,
        dictionary=dictionary,
        coherence='c_v'
    )
    score = cm.get_coherence()
    coherence_scores.append((n_topics, score))
    print(f"Topics: {n_topics}, Coherence: {score:.4f}")

#plotting

import matplotlib.pyplot as plt

x, y = zip(*coherence_scores)
plt.plot(x, y, marker='o')
plt.xlabel("Number of Topics")
plt.ylabel("Coherence Score (c_v)")
plt.title("Topic Coherence for Topic Range 5–20")
plt.grid(True)
plt.show()

"""## Visulializing Topics"""

tm_nolemma

topic_model.get_topic(4)

topic_model.visualize_barchart() #top_n_topics=20

topic_model.visualize_hierarchy()

topic_model.visualize_topics()

#50
topic_model.get_representative_docs(topic=4)

"""## Exploring Documents"""

docs_info = topic_model.get_document_info(documents)

topic_3_docs = docs_info[docs_info["Topic"] == 0]
#topic_3_docs

df_sorted = topic_3_docs.sort_values(by="Probability", ascending=False)
df_sorted

import random

def sample_snippets_by_topic(docs_info, topic_number=None, n=10, min_prob=0.0, seed=42):
    """
    Sample `n` random document snippets from a topic for codebook development.

    Parameters:
    - docs_info: DataFrame from topic_model.get_document_info()
    - topic_number: specific topic to sample from (int). If None, samples from all topics.
    - n: number of snippets to sample (int)
    - min_prob: minimum probability threshold to ensure relevance (float, 0.0–1.0)
    - seed: random seed for reproducibility (int)

    Returns:
    - DataFrame of sampled snippets
    """
    random.seed(seed)
    df = docs_info.copy()

    if topic_number is not None:
        df = df[df["Topic"] == topic_number]

    df = df[df["Probability"] >= min_prob]

    if len(df) == 0:
        print("No snippets found for this filter.")
        return pd.DataFrame()

    sample_indices = random.sample(list(df.index), min(n, len(df)))
    return df.loc[sample_indices][["Document", "Topic", "Probability"]].reset_index(drop=True)

sample = sample_snippets_by_topic(docs_info, topic_number=0, n=35, min_prob=0.3)

sample.iloc[34]["Document"]

doc = df_sorted.iloc[0]['Document']

doc

#saving snippets
snippets = pd.DataFrame(columns=["Topic", "Snippet"])

sample = sample_snippets_by_topic(docs_info, topic_number=3, n=35, min_prob=0.3)
snippets["Snippet"] = sample["Document"].tolist()
snippets["Topic"] = [3] * 35

snippets.head()

#Adding video name to snippet
file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/topic_4.csv"
topic_4 = pd.read_csv(file_path)

topic_4.head()

def vid_matching(text):
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  video = matches["doc_id"].iloc[0]
  return video

topic_4['Video'] = topic_4['Snippet'].apply(vid_matching)

topic_4.head()

file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/topic_4.csv"
topic_4.to_csv(file_path, index=False)

"""## Most Related Video"""

file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv"

chunked_df = pd.read_csv(file_path)

chunked_df.head()

documents = chunked_df["bigram_nolemmatext"].tolist()

#Creating new dataframe

top_vids = pd.DataFrame(columns=["Name", "Video1"])

top_vids["Name"]= tm_nolemma["Name"]

top_vids

videos = chunked_df["doc_id"].unique()

result = {item: 0 for item in videos}

docs_info = topic_model.get_document_info(documents)

topic_list = docs_info[docs_info["Topic"] == 2]["Document"]

def matching(text):
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  video = matches["doc_id"].iloc[0]

  #print(video + "-------")

  for video in matches["doc_id"]:
        result[video] = result.get(video, 0) + 1

  return result

for doc in topic_list:
  matching(doc)

sorted_scores = dict(sorted(result.items(), key=lambda x: x[1], reverse=True))
sorted_scores

top_vids

top_key = max(result, key=result.get)
print(top_key)

#Adding to the dictionary

top_vids.loc[4, "Video2"] = "episode-48-unfair-advantage.txt"

file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/top_vid.csv"
top_vids.to_csv(file_path, index=False)

"""## Removing duplicates?"""

file_path = "/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv"

chunked_df = pd.read_csv(file_path)

chunked_df.shape

chunked_df.head()

df_no_duplicates = chunked_df[~chunked_df['lower_text'].duplicated(keep=False)]

df_no_duplicates.shape