# -*- coding: utf-8 -*-
"""BertTopic.ipynb

Automatically generated by Colab.

# Imports and Installations
"""

#installations
!pip install bertopic
!pip install gensim

#imports
import nltk
nltk.download('punkt_tab')

#imports
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import glob
import os
import gensim
from gensim.models.phrases import Phrases, Phraser
from gensim import corpora
from gensim.models import CoherenceModel
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
import re
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import requests
import matplotlib.pyplot as plt
import random

#Connecting to google drive
from google.colab import drive
drive.mount('/content/drive')

"""# Creating DF of transcriptions, corresponding file path, and file name

"""

# Define the base directory for the videos
base_dir = '/content/drive/MyDrive/Emergency_Meeting_Deepgram'

#Using glob to collect all the text files
file_paths = glob.glob(os.path.join(base_dir, '**', '*.txt'), recursive=True)

#Creating a function to read the files
def read_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        return content

#Making a list of the documents where each index is a new transcription
documents = [read_file(fp) for fp in file_paths]

#Creating the DF
df = pd.DataFrame({'file_path': file_paths, 'text': documents})

#Creating a column for file names
file_names = []

#grabing the file name from the file path using REGEX
for path in df['file_path']:
    match = re.search(r'[^\\/]+$', path)
    file_name = match.group() if match else None
    file_names.append(file_name)

#Making the column in the df
df['file_name'] = file_names

df.head()

#making snippet DF - needed for BERTopic model

#Function to make the chunked texts
def chunk_dataframe(df, max_chars=800): #each chunk with a max of 800 characters
    snippets = []

    for idx, row in df.iterrows():
        doc_id = row['file_name']

        #Getting rid of extra whitespace
        text = re.sub(r'\s+', ' ', row['text']).strip()

        #Splitting text into sentences
        sentences = sent_tokenize(text)

        #Initalizing string
        chunk, chunk_id = "", 0
        #Looping through each sentence
        for sentence in sentences:
            #Checking if adding this sentence will still stay in the max char limit
            if len(chunk) + len(sentence) <= max_chars:
                #Adding sentence to current chunk
                chunk += " " + sentence
            #Adding information to snippit list when the chunk reaches max char limit
            else:
                snippets.append({
                    'doc_id': doc_id,
                    'chunk_id': chunk_id,
                    'text': chunk.strip()
                })
                #Adding one to chunk id
                chunk_id += 1
                #starting new chunk
                chunk = sentence
        #Outside the loop if there are extra sentences
        if chunk:
            #Saving final sentences to list
            snippets.append({
                'doc_id': doc_id,
                'chunk_id': chunk_id,
                'text': chunk.strip()
            })
    #Returning data frame with chunk information
    return pd.DataFrame(snippets)

#Chunking the df and saving it to a variable
chunked_df = chunk_dataframe(df)

"""# Preprosessing"""

#creating a column that is lowercased
chunked_df['lower_text'] = chunked_df['text'].str.lower()

#creating the stop words list using a list from github
stopwords_list = requests.get('https://gist.githubusercontent.com/rg089/35e00abf8941d72d419224cfd5b5925d/raw/12d899b70156fd0041fa9778d657330b024b959c/stopwords.txt').content
stop_words = set(stopwords_list.decode().splitlines())

#creating custom stop words list for common filler words
custom_stopwords = stop_words.union({'gon', 'yeah', 'fucking','bro', 'shit','thing', 'wan','ha',
                                     'andrew', 'tate', 'person','year', 'day','lot','fuck',
                                     'doe', 'time', 'good', 'talk', 'gonna','people', 'things',
                                     'wanna'})
custom_stopwords=list(custom_stopwords)

#Initialzing the vectorizer
vectorizer = CountVectorizer(stop_words=custom_stopwords)

#Tried out how it would look if the text was lemmatized - decided not to use it
import spacy
nlp = spacy.load('en_core_web_sm')

def lemmatize_text(text):
    doc = nlp(text)  # Process text with spaCy
    return " ".join([token.lemma_ for token in doc])  # Convert words to base form

#Adding the lemmatized text to the df
chunked_df['lemma_text'] = chunked_df['text'].apply(lemmatize_text)

#creating the list of the text
documents = chunked_df['lower_text'].tolist()

#Tokenizing each sentence
tokenized_texts = [word_tokenize(text) for text in documents]

#Training bigram model to campure meaningful two word associations
bigram_model = Phrases(tokenized_texts, min_count=10, threshold=50)
bigram_phraser = Phraser(bigram_model)

#Applying bigram model to my dataset
processed_token_lists = [bigram_phraser[doc] for doc in tokenized_texts]

#Convert processed tokens back into full sentences
processed_texts = [" ".join(tokens) for tokens in processed_token_lists]

#Making a new column with the bigram words
chunked_df['bigram_nolemmatext'] = processed_texts
#print(processed_texts)

#saving for later
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv'
chunked_df.to_csv(file_path, index=False)

chunked_df.head()

"""## Coherence Scores

Choosing the number of topics using coherence scores

"""

#Creating list of the documents
documents = chunked_df['bigram_nolemmatext'].tolist()

#Preprocessing the the text
cleaned_docs = topic_model._preprocess_text(documents)

#Initializing the analyzer
analyzer = topic_model.vectorizer_model.build_analyzer()
#Getting tokens
tokens = [analyzer(doc) for doc in cleaned_docs]

#To reduce the impact of frequent words
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

#Creating the dictionary
dictionary = corpora.Dictionary(tokens)
#Creating the corpus
corpus = [dictionary.doc2bow(token) for token in tokens]

coherence_scores = []

#Running the model for topics ranging 3 to 30
for n_topics in range(3, 30):
    #Building the model
    model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       vectorizer_model=vectorizer,
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30, #Algorithm for reducing dimensional space
                                       n_components=2,
                                       metric='cosine',
                                       min_dist=0.0),
                       hdbscan_model=HDBSCAN(min_cluster_size=45, #Controlling the number of topics through the cluster model
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

    topics, _ = model.fit_transform(documents)
    model = model.reduce_topics(documents, nr_topics=n_topics)

    #Getting topic words per topic
    topic_words = [
        [word for word, _ in model.get_topic(topic_id)]
        for topic_id in model.get_topics().keys()
        if topic_id != -1 #not including the -1 topic because its the 'leftover' topic
    ]

    #Calculating coherence scores
    cm = CoherenceModel(
        topics=topic_words,
        texts=tokens,
        corpus=corpus,
        dictionary=dictionary,
        coherence='c_v'
    )
    #Getting coherence score
    score = cm.get_coherence()
    coherence_scores.append((n_topics, score))
    print(f"Topics: {n_topics}, Coherence: {score:.4f}")

#Plotting the coherence score results
x, y = zip(*coherence_scores)
plt.plot(x, y, marker='o')
plt.xlabel('Number of Topics')
plt.ylabel('Coherence Score (c_v)')
plt.title('Topic Coherence for Topic Range 3–29')
plt.grid(True)
plt.show()

"""# Running the model"""

#BERT model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
#building the model
topic_model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       vectorizer_model=vectorizer,
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30,
                                       n_components=2,
                                       metric='cosine',
                                       min_dist=0.0),
                       hdbscan_model=HDBSCAN(min_cluster_size=45,
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

#Running the model on the documents
topics, probs = topic_model.fit_transform(documents)

#Saving the model
topic_model.save('/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics', save_embedding_model=True)

"""## Loading Saved Models"""

topic_model = BERTopic.load('/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics')

#Reducing the topics to 6 because it had the highest coherence score
topic_model.reduce_topics(documents, nr_topics=6)

tm_nolemma = topic_model.get_topic_info()

tm_nolemma

"""## Visulializing Topics"""

topic_model.get_topic(4)

topic_model.visualize_barchart()

topic_model.visualize_hierarchy()

topic_model.visualize_topics()

#50
topic_model.get_representative_docs(topic=4)

"""# Creating DF for each topic with all its related snippets and its corresponding video name

### Essential for the qualitative analysis
"""

#Getting doc info
docs_info = topic_model.get_document_info(documents)

#Getting all doc info for topic 0
topic_0_docs = docs_info[docs_info['Topic'] == 0]

#Sort the topics by probabbility
df_sorted = topic_0_docs.sort_values(by='Probability', ascending=False)
df_sorted

#Creating a function to gather all the topic snippets
# n is the number of snippets to sample
#Min_prob is the min probability threshold
#Seed is to keep it reproducable
def sample_snippets_by_topic(docs_info, topic_number=None, n=10, min_prob=0.0, seed=42):
    random.seed(seed)
    #Making a copy of the input data frame so the original doesnt change
    df = docs_info.copy()

    if topic_number is not None:
        #Keep only the rows with the corresponding topic number
        df = df[df['Topic'] == topic_number]
    #keeps rows with the correct probability
    df = df[df['Probability'] >= min_prob]

    #Randomly sample a set of rows
    sample_indices = random.sample(list(df.index), min(n, len(df)))

    #Return the randomly sampled rows with only these columns as a DF and reset the index
    return df.loc[sample_indices][['Document', 'Topic', 'Probability']].reset_index(drop=True)

#Making a function to make the video title to text snippet
def vid_matching(text):
  #Grabbing the rows where the text matches exactly
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  #Grabbing the video id from the the row
  video = matches['doc_id'].iloc[0]
  #returning video name
  return video

#Applying the sample function
sample = sample_snippets_by_topic(docs_info, topic_number=0, n=35, min_prob=0.3)

#Looking at example
sample.iloc[34]['Document']

#Grabbing the df for topic 3
topic_3 = sample_snippets_by_topic(docs_info, topic_number=3, n=35, min_prob=0.3)

#Adding the video name column to DF
topic_3['Video'] = topic_3['Document'].apply(vid_matching)

#Saving topic list as a csv file
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/topic_3.csv'
topic_3.to_csv(file_path, index=False)

"""# Looking at the number of snippets per video per topic"""

#Reading in the chunked df
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv'
chunked_df = pd.read_csv(file_path)

#Building list of documents
documents = chunked_df['bigram_nolemmatext'].tolist()

#Creating a dictionary to count the video
videos = chunked_df['doc_id'].unique()

result = {item: 0 for item in videos}

#Get topic assignments for every document
docs_info = topic_model.get_document_info(documents)

#Chosing the topic to look at
topic_list = docs_info[docs_info['Topic'] == 2]['Document']

#Function count the number of snippets per video
def matching(text):
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  video = matches['doc_id'].iloc[0]

  for video in matches['doc_id']:
        result[video] = result.get(video, 0) + 1

  return result

#running the function othe topic list
for doc in topic_list:
  matching(doc)

#Number of snippets per video for topic 2
sorted_scores = dict(sorted(result.items(), key=lambda x: x[1], reverse=True))
sorted_scores
